#!/usr/bin/env python3
# Modules
import requests, urllib3
urllib3.disable_warnings()
import sys
from termcolor import colored, cprint



# M1 FUZZER
cprint("""
█                                                               github.com/1momo7


                           888b     d888  d888        8888888888 888     888 8888888888P 8888888888P 8888888888 8888888b.  
                           8888b   d8888 d8888        888        888     888       d88P        d88P  888        888   Y88b 
                           88888b.d88888   888        888        888     888      d88P        d88P   888        888    888 
                           888Y88888P888   888        8888888    888     888     d88P        d88P    8888888    888   d88P 
                           888 Y888P 888   888        888        888     888    d88P        d88P     888        8888888P"  
                           888  Y8P  888   888        888        888     888   d88P        d88P      888        888 T88b   
                           888   "   888   888        888        Y88b. .d88P  d88P        d88P       888        888  T88b  
                           888       888 8888888      888         "Y88888P"  d8888888888 d8888888888 8888888888 888   T88b 
                                                                                                
                                                                                            
                                                                github.com/yTarik0
""", 'white')



# HTTP request

def req(url):
    try:
        r = requests.get(url, verify=False)
    except:
        return
    responselength = len(r.text)
    
    if r.status_code != 200 and r.status_code != 404:
        print("\r", "FOUND:" ,url,"|" ,"STATUS CODE:",r.status_code,"|","Responselength:",responselength)        # SORTING OUT NOT WORKING DIRECTORIES / SUBDOMAINS
    else:
        print("\r","Fuzzing...",url,end="                       ")


inp = input("M1: ")
domain = inp.split(" ")[0]


if not ("http://") in inp:
    cprint("""Usage: 
    m1 
    <url> [command]
    
Available Commands:
    FUZZ. /FUZZ       Uses fuzzing mode. Replaces the keyword FUZZ in the URL 
    -php              Also fuzzing for php directories    | cant do both yet
    -apache           Also fuzzing for apache directories | cant do both yet""", "blue")
    exit()




# Target
if not ("FUZZ") in domain:
            print("Please include FUZZ to tell me what you are FUZZING for...")
            exit()


if ("FUZZ.") in domain:
    if ("php") in inp:
        cprint("Invalid command. Try -help", 'red')
        exit()
    elif ("apache") in inp:
        cprint("Invalid command. Try -help", 'red')
        exit()
    else:
        with open("/usr/share/seclists/Discovery/DNS/subdomains-top1million-110000.txt") as data:          # CHANGE THIS WORDLIST
            content = data.readlines()
            for sub in content:
                cleansub = sub.replace("\n", "")
                cleandomain = domain.replace("FUZZ", cleansub)
                req(cleandomain)


if ("/FUZZ") in domain:
    if ("apache" or "-apache") in inp:
        with open("/usr/share/wordlists/dirbuster/apachewordlist") as data:          # CHANGE THIS WORDLIST
            content = data.readlines()
            for word in content:
                cleanword = word.replace("\n", "")
                cleandomain = domain.replace("FUZZ", cleanword)
                req(cleandomain)
    elif ("php" or "-php") in inp:
        with open("/usr/share/wordlists/dirbuster/wordlistphp") as data:          # CHANGE THIS WORDLIST
            content = data.readlines()
            for word in content:
                cleanword = word.replace("\n", "")
                cleandomain = domain.replace("FUZZ", cleanword)
                req(cleandomain)
    else:
        with open("/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt") as data:          # CHANGE THIS WORDLIST
            content = data.readlines()
            for word in content:
                cleanword = word.replace("\n", "")
                cleandomain = domain.replace("FUZZ", cleanword)
                req(cleandomain)


# Subdomains

 
